FROM node:lts as builder

### copy vue
WORKDIR /app
COPY webui webui

### build vue
WORKDIR /app/webui
RUN yarn run build-prod


### serve the files
FROM nginx:stable
COPY --from=builder /app/webui/dist /usr/share/nginx/html
EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]